[package]
name = "mapdiffbot2"
version = "0.1.0"
edition = "2021"
license = "MIT"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.171", features = ["derive"] }
serde_json = { version = "1.0.100"}
toml = "0.7.6"
octocrab = "0.25.1"
flume = "0.10.14"
dmm-tools = { git = "https://github.com/jupyterkat/SpacemanDMM/" }
dreammaker = { git = "https://github.com/jupyterkat/SpacemanDMM/" }
ahash = "0.8.3"
path-absolutize = "3.1.0"
jsonwebtoken = "8.3.0"
lazy_static = "1.4.0"
eyre = "0.6.8"
simple-eyre = "0.3.1"
rayon = "1.7.0"
derive_builder = "0.12.0"
once_cell = "1.18.0"
image = "0.24.6"
bytemuck = "1.13.1"
glob = "0.3.1"
diffbot_lib = { path = "../diffbot_lib" }
git2 = "0.17.2"
yaque = { git = "https://github.com/jupyterkat/yaque" }
walkdir = "2.3.3"
delay_timer = "0.11.4"
hex = { version = "0.4.3", features = ["serde"] }
itertools = "0.11.0"
indexmap = { version = "2.0.0", features = ["rayon"] }

actix-web = "4.3.1"
actix-files = "0.6.2"

object_store = { version = "0.6.1", features = ["azure"] }

mysql_async = "0.32.2"
time = "0.3.23"

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = "0.5.0"

[dev-dependencies]
tempfile = "3"
